AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - Gemfile
    - Gemfile.lock
    - spec/dummy/db/schema.rb
    - spec/dummy/bin/**/*
    - spec/dummy/config/environments/**/*
    - vendor/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false
